% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\newsavebox\pandoc@box
\newcommand*\pandocbounded[1]{% scales image to fit in text height/width
  \sbox\pandoc@box{#1}%
  \Gscale@div\@tempa{\textheight}{\dimexpr\ht\pandoc@box+\dp\pandoc@box\relax}%
  \Gscale@div\@tempb{\linewidth}{\wd\pandoc@box}%
  \ifdim\@tempb\p@<\@tempa\p@\let\@tempa\@tempb\fi% select the smaller of both
  \ifdim\@tempa\p@<\p@\scalebox{\@tempa}{\usebox\pandoc@box}%
  \else\usebox{\pandoc@box}%
  \fi%
}
% Set default figure placement to htbp
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage{wrapfig}
\usepackage{float}
\usepackage{colortbl}
\usepackage{pdflscape}
\usepackage{tabu}
\usepackage{threeparttable}
\usepackage{threeparttablex}
\usepackage[normalem]{ulem}
\usepackage{makecell}
\usepackage{xcolor}
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={ME613A - Análise de Regressão},
  pdfauthor={Profa. Tatiana Benaglia},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{ME613A - Análise de Regressão}
\author{Profa. Tatiana Benaglia}
\date{Atividade Prática 02 - 2S2025 - 10/09/2025}

\begin{document}
\maketitle

\subsection{Introdução: Relação entre palmo e
altura}\label{introduuxe7uxe3o-relauxe7uxe3o-entre-palmo-e-altura}

Será que a medida do seu palmo está associada com a sua altura?

Para verificar esta possível relação, foram medidas a largura do palmo e
a altura (em polegadas) de 167 estudantes universitários. Também
registraram o gênero do estudante. Os dados estão no arquivo
\texttt{handheight.txt} em anexo.

Considere como variável resposta a altura (\texttt{Height}) e como
variável preditora a larura do palmo (\texttt{HandSpan}).

\subsection{Atividades}\label{atividades}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Leia o conjunto de dados no R e faça um gráfico de dispersão entre
  altura e largura do palmo. Comente.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Leer archivo sin encabezado}
\NormalTok{dados\_hand }\OtherTok{\textless{}{-}}\NormalTok{ readr}\SpecialCharTok{::}\FunctionTok{read\_table}\NormalTok{(}
  \StringTok{"handheight.txt"}
\NormalTok{)}


\CommentTok{\# Ver las primeras filas}
\FunctionTok{head}\NormalTok{(dados\_hand)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 6 x 3
##   Sex    Height HandSpan
##   <chr>   <dbl>    <dbl>
## 1 Female     68     21.5
## 2 Male       71     23.5
## 3 Male       73     22.5
## 4 Female     64     18  
## 5 Male       68     23.5
## 6 Female     59     20
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Dispersión Height vs HandSpan}
\FunctionTok{ggplot}\NormalTok{(dados\_hand, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ HandSpan, }\AttributeTok{y =}\NormalTok{ Height)) }\SpecialCharTok{+}
  \FunctionTok{geom\_point}\NormalTok{(}\AttributeTok{alpha =} \FloatTok{0.7}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{x =} \StringTok{"Largura do palmo (HandSpan, pol.)"}\NormalTok{, }\AttributeTok{y =} \StringTok{"Altura (Height, pol.)"}\NormalTok{,}
       \AttributeTok{title =} \StringTok{"Dispersão: Altura vs Largura do Palmo"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{CuadraoyLucasLista2ATE6_files/figure-latex/unnamed-chunk-1-1.pdf}}
\textbf{INTERPRETACION DE LA GRAFICA} No nosso gráfico, o eixo X é a
\textbf{largura do palmo} e o eixo Y é a \textbf{altura da pessoa}.
Pode-se observar como se forma uma linha com tendência positiva, o que
nos leva a entender que, quanto maior a largura do palmo, maior será a
altura. A nuvem pode ser considerada razoavelmente homogênea, sem
curvatura.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{1}
\tightlist
\item
  Ajuste o modelo de regressão linear simples utilizando a função
  \texttt{lm()} e apresente os resultados. \textbf{Dica}: use a função
  \texttt{summary()}.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{m }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(Height }\SpecialCharTok{\textasciitilde{}}\NormalTok{ HandSpan, }\AttributeTok{data =}\NormalTok{ dados\_hand)}
\FunctionTok{summary}\NormalTok{(m)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = Height ~ HandSpan, data = dados_hand)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -7.727 -1.727 -0.167  1.493  7.493 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(>|t|)    
## (Intercept)   35.525      2.316    15.3   <2e-16 ***
## HandSpan       1.560      0.111    14.1   <2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 2.74 on 165 degrees of freedom
## Multiple R-squared:  0.547,  Adjusted R-squared:  0.544 
## F-statistic:  199 on 1 and 165 DF,  p-value: <2e-16
\end{verbatim}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{2}
\tightlist
\item
  Apresente a tabela ANOVA e identifique nesta tabela as somas de
  quadrados \(SQReg\), \(SQE\) e \(SQT\). Qual a estimativa da variância
  \(\sigma^2\)? \textbf{Dica}: use a função \texttt{anova()}.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{anova}\NormalTok{(m)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Analysis of Variance Table
## 
## Response: Height
##            Df Sum Sq Mean Sq F value Pr(>F)    
## HandSpan    1   1500    1500     199 <2e-16 ***
## Residuals 165   1243       8                   
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
\end{verbatim}

**INTERPRETACION DE LA TABLA* Identificação: \(SQReg = 1500\),
\(SQE = 1243\) e, como sabemos pela teoria, \(SQT\) é a soma dos valores
de \(SQReg\) e \(SQE\), que seria \(2743\). A estimativa da variância
\(\sigma^2\) é o quadrado médio do Erro (QME), isto é, a Soma de
Quadrados do Erro dividida pelos seus graus de liberdade; neste caso, o
número de estudantes menos 2, ou seja, \(gl_E = 165\). Portanto, a
estimativa da variância \(\sigma^2\) é \(7{,}533\).

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{3}
\tightlist
\item
  Apresente um gráfico de dispersão dos dados juntamente com a reta de
  regressão ajustada, usando a função \texttt{geom\_smooth()}. Escreva
  um parágrafo com as interpretação dos parâmetros.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(ggplot2)}

\FunctionTok{ggplot}\NormalTok{(dados\_hand, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ HandSpan, }\AttributeTok{y =}\NormalTok{ Height)) }\SpecialCharTok{+}
  \FunctionTok{geom\_point}\NormalTok{(}\AttributeTok{alpha =} \FloatTok{0.7}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{geom\_smooth}\NormalTok{(}\AttributeTok{method =} \StringTok{"lm"}\NormalTok{, }\AttributeTok{se =} \ConstantTok{TRUE}\NormalTok{) }\SpecialCharTok{+}  \CommentTok{\# banda = IC(95\%) para la media E[Y|X]}
  \FunctionTok{labs}\NormalTok{(}
    \AttributeTok{title =} \StringTok{"Dispersão com reta de regressão: Height \textasciitilde{} HandSpan"}\NormalTok{,}
    \AttributeTok{x =} \StringTok{"HandSpan (pol.)"}\NormalTok{,}
    \AttributeTok{y =} \StringTok{"Height (pol.)"}
\NormalTok{  ) }\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{CuadraoyLucasLista2ATE6_files/figure-latex/unnamed-chunk-4-1.pdf}}

**INTERPRETACION DE LA TABLA* O gráfico de dispersão mostra uma relação
aproximadamente linear e positiva entre a \textbf{largura do palmo} e a
\textbf{altura}. A reta ajustada representa a média \(E(Y \mid X)\) do
modelo \(Y=\beta_0+\beta_1 X+\varepsilon\). Da saída do \textit{inciso}
2, vemos que a reta ajustada é \(Y=35{,}525+1{,}560\,X\), cujo
coeficiente angular é \(\beta_1=1{,}560\) e o intercepto
\(\beta_0=35{,}525\); isto é a altura média estimada quando \(X=0\) (sem
sentido prático; a interpretação é apenas algébrica). A faixa sombreada
é o IC(95\%) para a resposta média \(E(Y \mid X)\); é mais estreita
perto da média de \(X\) e se alarga ao se afastar, como prevê a
variância de \(\hat{Y}_h\).

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{4}
\item
  Faça a análise de resíduos. Vamos começar pelos gráficos descritos no
  itens abaixo. O que você observa? Existe alguma tendência aparente nos
  gráficos?

  \begin{enumerate}
  \def\labelenumii{\alph{enumii})}
  \tightlist
  \item
    Resíduos versus a variável preditora.
  \item
    Resíduos versus valores peditos.
  \end{enumerate}
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{m   }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(Height }\SpecialCharTok{\textasciitilde{}}\NormalTok{ HandSpan, }\AttributeTok{data =}\NormalTok{ dados\_hand)}
\NormalTok{res }\OtherTok{\textless{}{-}} \FunctionTok{residuals}\NormalTok{(m)}
\NormalTok{fit }\OtherTok{\textless{}{-}} \FunctionTok{fitted}\NormalTok{(m)}

\CommentTok{\# 5a) Residuos vs variable predictora}
\FunctionTok{plot}\NormalTok{(dados\_hand}\SpecialCharTok{$}\NormalTok{HandSpan, res,}
     \AttributeTok{xlab =} \StringTok{"HandSpan (pol.)"}\NormalTok{, }\AttributeTok{ylab =} \StringTok{"Residuos"}\NormalTok{,}
     \AttributeTok{main =} \StringTok{"Residuos vs variable predictora"}\NormalTok{)}
\FunctionTok{abline}\NormalTok{(}\AttributeTok{h =} \DecValTok{0}\NormalTok{, }\AttributeTok{lty =} \DecValTok{2}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{CuadraoyLucasLista2ATE6_files/figure-latex/unnamed-chunk-5-1.pdf}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# 5b) Residuos vs valores predichos}
\FunctionTok{plot}\NormalTok{(fit, res,}
     \AttributeTok{xlab =} \StringTok{"Valores predichos"}\NormalTok{, }\AttributeTok{ylab =} \StringTok{"Residuos"}\NormalTok{,}
     \AttributeTok{main =} \StringTok{"Residuos vs valores predichos"}\NormalTok{)}
\FunctionTok{abline}\NormalTok{(}\AttributeTok{h =} \DecValTok{0}\NormalTok{, }\AttributeTok{lty =} \DecValTok{2}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{CuadraoyLucasLista2ATE6_files/figure-latex/unnamed-chunk-5-2.pdf}}
\emph{INTERPRETACION DE LAS GRAFICA}

\paragraph{a) Resíduos versus a variável preditora.}

A nuvem está centrada em torno de 0, não tem curvaturas nem inclinações,
portanto não há tendência aparente. A dispersão é mais ou menos
constante ao longo de \textit{HandSpan}, com alguns resíduos extremos
(cerca de \(\pm 7\)). Em conjunto, o gráfico é consistente com a
linearidade de \(E(Y \mid X)\) e com homocedasticidade aproximada.

\paragraph{b) Resíduos versus valores preditos.}

A nuvem também está centrada em torno de 0 e não apresenta curvaturas
nem inclinações, de modo que não há evidência de não linearidade do
modelo. Também não se observa formação de ``cone'\,' que indique
heterocedasticidade, confirmando o do primeiro inciso: a variabilidade é
mais ou menos constante, o que é compatível com homocedasticidade. Em
conclusão, o gráfico respalda que os pressupostos de linearidade e de
variância aproximadamente constante são razoáveis.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{5}
\item
  Analise a suposição de normalidade dos resíduos das seguintes formas:

  \begin{enumerate}
  \def\labelenumii{\alph{enumii})}
  \tightlist
  \item
    Graficamente: boxplot, histograma e QQ-plot. Comente.
  \item
    Teste de hipótese. Escolha um teste apropriado, aplique e comente.
  \end{enumerate}
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{res }\OtherTok{\textless{}{-}} \FunctionTok{residuals}\NormalTok{(m)}
\FunctionTok{par}\NormalTok{(}\AttributeTok{mfrow=}\FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{3}\NormalTok{))}
\FunctionTok{boxplot}\NormalTok{(res, }\AttributeTok{main=}\StringTok{"Boxplot dos resíduos"}\NormalTok{)}
\FunctionTok{hist}\NormalTok{(res, }\AttributeTok{main=}\StringTok{"Histograma dos resíduos"}\NormalTok{, }\AttributeTok{xlab=}\StringTok{"Resíduos"}\NormalTok{)}
\FunctionTok{qqnorm}\NormalTok{(res); }\FunctionTok{qqline}\NormalTok{(res)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{CuadraoyLucasLista2ATE6_files/figure-latex/unnamed-chunk-6-1.pdf}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{par}\NormalTok{(}\AttributeTok{mfrow=}\FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{1}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\emph{INTERPRETACION DE LAS GRAFICA}
\textbf{a) Graficamente: boxplot, histograma e QQ-plot. Comente.}

\textbf{Boxplot:} está centrado perto de 0 e é bastante simétrico;
aparecem poucos pontos extremos nas caudas. Isso sugere que os resíduos
não apresentam assimetrias marcantes.

\textbf{Histograma:} pode-se ver que forma aproximadamente uma campana,
centrada em 0, coerente com a distribuição normal dos resíduos.

\textbf{QQ-plot:} pode-se ver como os pontos seguem bem a reta de
regressão, com alguns desvios nas caudas, sem apresentar curvaturas.

\begin{enumerate}
\def\labelenumi{\alph{enumi})}
\setcounter{enumi}{1}
\tightlist
\item
  Teste de hipótese. Escolha um teste apropriado, aplique e comente.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Asumiendo que ya ajustaste:}
\CommentTok{\# m \textless{}{-} lm(Height \textasciitilde{} HandSpan, data = dados\_hand)}

\CommentTok{\# 1) Residuos crudos}
\NormalTok{res }\OtherTok{\textless{}{-}} \FunctionTok{residuals}\NormalTok{(m)           }\CommentTok{\# o: res \textless{}{-} resid(m)}
\FunctionTok{shapiro.test}\NormalTok{(res)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Shapiro-Wilk normality test
## 
## data:  res
## W = 1, p-value = 0.6
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# (opcional) Residuos estandarizados}
\NormalTok{rstd }\OtherTok{\textless{}{-}} \FunctionTok{rstandard}\NormalTok{(m)}
\FunctionTok{shapiro.test}\NormalTok{(rstd)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Shapiro-Wilk normality test
## 
## data:  rstd
## W = 1, p-value = 0.6
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# (opcional) Mini{-}reporte automático}
\NormalTok{p }\OtherTok{\textless{}{-}} \FunctionTok{shapiro.test}\NormalTok{(res)}\SpecialCharTok{$}\NormalTok{p.value}
\FunctionTok{cat}\NormalTok{(}\FunctionTok{sprintf}\NormalTok{(}\StringTok{"Shapiro–Wilk p{-}valor = \%.4f {-}\textgreater{} \%s}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{,}
\NormalTok{            p, }\FunctionTok{ifelse}\NormalTok{(p }\SpecialCharTok{\textless{}} \FloatTok{0.05}\NormalTok{, }\StringTok{"rechazo de normalidad"}\NormalTok{, }\StringTok{"no se rechaza normalidad"}\NormalTok{)))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Shapiro–Wilk p-valor = 0.5706 -> no se rechaza normalidad
\end{verbatim}

Escolhemos o teste de Shapiro--Wilk; o que nos importa verificar é a
hipótese de que os erros (e portanto os resíduos) seguem uma Normal. Seu
estatístico baseia-se na correlação entre os resíduos ordenados e os
quantis normais esperados; se a correlação é alta, há evidência de
normalidade.

\textbf{Hipóteses.} \[
H_0:\ \text{os erros (e portanto os resíduos) seguem uma Normal},
\qquad
H_1:\ \text{não normalidade}.
\]

\textbf{Resultados do teste.} Aplicado aos \emph{resíduos brutos} e aos
\emph{padronizados}, obtenho \(W \approx 0{,}993\) e
\(p \approx 0{,}571\) em ambos os casos.

\textbf{Decisão} (\(\alpha=0{,}05\)): não se rejeita \(H_0\).

\textbf{Conclusão.} A evidência é consistente com normalidade dos
resíduos, em coerência com o diagnóstico gráfico (boxplot, histograma e
QQ-plot), onde os pontos seguem razoavelmente a \textbf{reta}.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{6}
\item
  Verifique através de um teste de hipótese a suposição de
  homocedasticidade.
\item
  É possível aplicar o teste F de falta de ajuste para esse dados? Se
  sim, apresente a tabela ANOVA com a decomposição da SQE em SQFA e
  SQEp. Indique quais hipóteses estão sendo testadas, a estatística do
  teste e conclusão.
\item
  Depois de verificar as suposições do modelo através da análise dos
  resíduos, faça agora um teste de hipótese para checar se a relação
  linear entre \texttt{HandSpan} e \texttt{Height} é significativa.
\item
  Qual é a altura média de estudantes cuja largura do palmo é 17, 21 e
  24 polegadas, respectivamente. Apresente também um intervalo de 95\%
  de confiança para estes casos e compare-os. \textbf{Dica}: usar a
  função \texttt{predict()}.
\item
  Para um novo estudante, qual a estimativa de sua altura dado que sua
  largura do palmo é 17, 21 e 24 polegadas, respectivamente. Apresente
  também um intervalo de predição de 95\% para esses casos. Compare com
  os intervalos de confiança obtidos no item anterior. \textbf{Dica}:
  usar a função \texttt{predict()} modificando o arguemnto
  \texttt{interval}.
\item
  Apresente um gráfico de dispersão, juntamente com a reta ajustada e a
  banda de confiança para estimação da resposta média e o intervalo de
  predição para uma nova observação, ambos com nível de confiança de
  95\%.
\end{enumerate}

\end{document}
